"""Generate requirements-conductor.txt from pyproject.toml's train extra."""

from __future__ import annotations

import argparse
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT = REPO_ROOT / "requirements-conductor.txt"

HEADER = """\
# Generated by scripts/generate_conductor_requirements.py — do not edit by hand.
# Conductor GRPO retraining environment (isolated from the main stack).
# Source of truth: [project.optional-dependencies].train in pyproject.toml.
# transformers<5 keeps trl GRPO optional imports stable.
"""


def _canonical_name(spec: str) -> str:
    """Extract the pip-canonical package name from a requirement spec."""
    for index, char in enumerate(spec):
        if not (char.isalnum() or char in "-_."):
            spec_name = spec[:index]
            break
    else:
        spec_name = spec
    return spec_name.replace("_", "-")


def _load_train_specs(pyproject_path: Path) -> list[str]:
    with pyproject_path.open("rb") as handle:
        data = tomllib.load(handle)
    train = data["project"]["optional-dependencies"]["train"]
    return [spec.replace("math_verify", "math-verify") for spec in train]


def generate(pyproject_path: Path) -> str:
    specs = _load_train_specs(pyproject_path)
    return HEADER + "\n".join(sorted(specs, key=lambda spec: _canonical_name(spec).lower())) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Path to write the generated requirements file (default: %(default)s)",
    )
    args = parser.parse_args()

    pyproject_path = REPO_ROOT / "pyproject.toml"
    content = generate(pyproject_path)
    args.output.write_text(content)


if __name__ == "__main__":
    main()
